# Generated by Django 4.1.7 on 2023-03-06 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tag_project_vote_ratio_project_vote_total_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
